<template><div v-if="open" class="overlay" @click.self="close"><div class="palette"><div class="search"><SearchIcon/><input ref="input" v-model="query" placeholder="输入命令、页面或操作…" @keydown.down.prevent="step(1)" @keydown.up.prevent="step(-1)" @keydown.enter.prevent="run(filtered[index])"/></div><div class="items"><button v-for="(c,i) in filtered" :key="c.id" :class="{active:i===index}" @mouseenter="index=i" @click="run(c)"><component :is="c.icon"/><span><strong>{{c.title}}</strong><small>{{c.hint}}</small></span><kbd v-if="c.key">{{c.key}}</kbd></button><div v-if="!filtered.length" class="none">没有匹配的命令</div></div></div></div></template>
<script setup lang="ts">import {computed,nextTick,onBeforeUnmount,onMounted,ref,watch} from 'vue'; import {useRouter} from 'vue-router'; import {SearchIcon,ScissorsIcon,SettingsIcon,AppWindowIcon,Undo2Icon,Redo2Icon,FolderOpenIcon,RefreshCwIcon,ChevronsDownUpIcon,ChevronsUpDownIcon} from 'lucide-vue-next'; import {useEspansoStore} from '@/store/useEspansoStore'; import * as platform from '@/services/platformService'; import {controlEspanso} from '@/services/espansoInstallService';
const router=useRouter(),store=useEspansoStore(); const open=ref(false),query=ref(''),index=ref(0),input=ref<HTMLInputElement|null>(null);
type Cmd={id:string;title:string;hint:string;key?:string;icon:any;disabled?:()=>boolean;action:()=>any}; const cmds=computed<Cmd[]>(()=>[
{id:'snippets',title:'片段管理',hint:'打开片段编辑器',icon:ScissorsIcon,action:()=>router.push('/snippets')},{id:'apps',title:'应用配置管理器',hint:'管理 config/*.yml 应用规则',icon:AppWindowIcon,action:()=>router.push('/apps')},{id:'settings',title:'设置',hint:'打开 Easy Espanso 设置',icon:SettingsIcon,action:()=>router.push('/settings')},
{id:'undo',title:'撤销',hint:store.history.undoStack.at(-1)?.label||'没有可撤销操作',key:'Ctrl+Z',icon:Undo2Icon,disabled:()=>!store.history.canUndo,action:()=>store.undo()},{id:'redo',title:'重做',hint:store.history.redoStack.at(-1)?.label||'没有可重做操作',key:'Ctrl+Y',icon:Redo2Icon,disabled:()=>!store.history.canRedo,action:()=>store.redo()},
{id:'open',title:'在文件管理器中打开配置目录',hint:store.state.configRootDir||'未选择工作区',icon:FolderOpenIcon,disabled:()=>!store.state.configRootDir,action:()=>platform.openInExplorer(store.state.configRootDir!)},{id:'restart',title:'重启 Espanso',hint:'重新加载配置并重启服务',icon:RefreshCwIcon,action:()=>controlEspanso('restart')},
{id:'expand',title:'展开全部配置',hint:'展开左侧配置树',icon:ChevronsUpDownIcon,action:()=>store.expandAllNodes()},{id:'collapse',title:'折叠全部配置',hint:'折叠左侧配置树',icon:ChevronsDownUpIcon,action:()=>store.collapseAllNodes()}]);
const filtered=computed(()=>{const q=query.value.trim().toLowerCase();return cmds.value.filter(c=>!c.disabled?.()&&(!q||`${c.title} ${c.hint}`.toLowerCase().includes(q)))}); function close(){open.value=false} function show(){open.value=true;query.value='';index.value=0;nextTick(()=>input.value?.focus())} function run(c?:Cmd){if(!c)return;close();c.action()} function step(d:number){if(filtered.value.length)index.value=(index.value+d+filtered.value.length)%filtered.value.length} function keys(e:KeyboardEvent){const mod=e.ctrlKey||e.metaKey;if(mod&&e.key.toLowerCase()==='k'){e.preventDefault();open.value?close():show()} else if(mod&&e.key.toLowerCase()==='z'&&!e.shiftKey&&!(e.target instanceof HTMLInputElement)&&!(e.target instanceof HTMLTextAreaElement)){e.preventDefault();store.undo()} else if(mod&&(e.key.toLowerCase()==='y'||(e.shiftKey&&e.key.toLowerCase()==='z'))&&!(e.target instanceof HTMLInputElement)&&!(e.target instanceof HTMLTextAreaElement)){e.preventDefault();store.redo()} else if(e.key==='Escape'&&open.value)close()} onMounted(()=>window.addEventListener('keydown',keys));onBeforeUnmount(()=>window.removeEventListener('keydown',keys));watch(filtered,()=>index.value=0);</script>
<style scoped>.overlay{position:fixed;inset:0;background:#0008;z-index:1000;display:flex;justify-content:center;padding-top:12vh}.palette{width:min(640px,90vw);height:max-content;max-height:68vh;background:hsl(var(--popover));border:1px solid hsl(var(--border));border-radius:14px;box-shadow:0 20px 60px #0006;overflow:hidden}.search{display:flex;align-items:center;gap:10px;padding:14px;border-bottom:1px solid hsl(var(--border))}.search svg{width:20px}.search input{flex:1;background:transparent;outline:0;font-size:16px}.items{padding:7px;max-height:55vh;overflow:auto}.items button{width:100%;display:flex;align-items:center;gap:12px;text-align:left;padding:10px;border-radius:8px}.items button.active{background:hsl(var(--accent))}.items button>svg{width:19px}.items span{display:grid;flex:1}.items small{color:hsl(var(--muted-foreground))}.items kbd{font-size:11px;border:1px solid hsl(var(--border));padding:2px 5px;border-radius:5px}.none{padding:25px;text-align:center;color:hsl(var(--muted-foreground))}</style>
